export interface NavItem {
  label: string;
  translationKey?: string;
  icon: string;
  route: string;
  roles?: string[];
  children?: NavItem[];
}

export const NAV_ITEMS: NavItem[] = [
  {
    label: 'Dashboard',
    translationKey: 'NAV.DASHBOARD',
    icon: 'dashboard',
    route: '/dashboard',
  },
  {
    label: 'Products',
    translationKey: 'NAV.PRODUCTS',
    icon: 'inventory_2',
    route: '/products',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Inventory',
    translationKey: 'NAV.INVENTORY',
    icon: 'warehouse',
    route: '/inventory',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Purchases',
    translationKey: 'NAV.PURCHASES',
    icon: 'shopping_cart',
    route: '/purchases',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Sales',
    translationKey: 'NAV.SALES',
    icon: 'receipt',
    route: '/sales',
    roles: ['admin', 'manager', 'cashier'],
  },
  {
    label: 'POS',
    translationKey: 'NAV.POS',
    icon: 'point_of_sale',
    route: '/pos',
    roles: ['admin', 'manager', 'cashier'],
  },
  {
    label: 'Reports',
    translationKey: 'NAV.REPORTS',
    icon: 'assessment',
    route: '/reports',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Expenses',
    translationKey: 'NAV.EXPENSES',
    icon: 'receipt_long',
    route: '/expenses',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Cash Register',
    translationKey: 'NAV.CASH_REGISTER',
    icon: 'point_of_sale',
    route: '/cash-register',
    roles: ['admin', 'manager', 'cashier'],
  },
  {
    label: 'Contacts',
    translationKey: 'NAV.CONTACTS',
    icon: 'people',
    route: '/contacts',
    roles: ['admin', 'manager', 'cashier'],
  },
  {
    label: 'Business',
    translationKey: 'NAV.BUSINESS',
    icon: 'business',
    route: '/business',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Settings',
    translationKey: 'NAV.SETTINGS',
    icon: 'settings',
    route: '/settings',
    roles: ['admin'],
  },
  {
    label: 'Import / Export',
    translationKey: 'NAV.IMPORT_EXPORT',
    icon: 'import_export',
    route: '/import-export',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Notifications',
    translationKey: 'NAV.NOTIFICATIONS',
    icon: 'notifications',
    route: '/notifications',
    roles: ['admin', 'manager', 'cashier'],
  },
  {
    label: 'Tax Rates',
    translationKey: 'NAV.TAX_RATES',
    icon: 'percent',
    route: '/tax-rates',
    roles: ['admin'],
  },
  {
    label: 'Stock Adjustments',
    translationKey: 'NAV.STOCK_ADJUSTMENTS',
    icon: 'tune',
    route: '/stock-adjustments',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Stock Transfers',
    translationKey: 'NAV.STOCK_TRANSFERS',
    icon: 'swap_horiz',
    route: '/stock-transfers',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Payments',
    translationKey: 'NAV.PAYMENTS',
    icon: 'payments',
    route: '/payments',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Barcodes',
    translationKey: 'NAV.BARCODES',
    icon: 'qr_code',
    route: '/products/barcodes',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Accounting',
    translationKey: 'NAV.ACCOUNTING',
    icon: 'account_balance',
    route: '/accounting',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Restaurant',
    translationKey: 'NAV.RESTAURANT',
    icon: 'restaurant',
    route: '/restaurant',
    roles: ['admin', 'manager'],
  },
  {
    label: 'CRM',
    translationKey: 'NAV.CRM',
    icon: 'people_alt',
    route: '/crm',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Manufacturing',
    translationKey: 'NAV.MANUFACTURING',
    icon: 'precision_manufacturing',
    route: '/manufacturing',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Repair',
    translationKey: 'NAV.REPAIR',
    icon: 'build',
    route: '/repair',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Assets',
    translationKey: 'NAV.ASSETS',
    icon: 'inventory_2',
    route: '/asset-management',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Projects',
    translationKey: 'NAV.PROJECTS',
    icon: 'folder_open',
    route: '/project',
    roles: ['admin', 'manager'],
  },
  {
    label: 'HR & Docs',
    translationKey: 'NAV.ESSENTIALS',
    icon: 'badge',
    route: '/essentials',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Hotel (HMS)',
    translationKey: 'NAV.HMS',
    icon: 'hotel',
    route: '/hms',
    roles: ['admin', 'manager'],
  },
  {
    label: 'Superadmin',
    translationKey: 'NAV.SUPERADMIN',
    icon: 'admin_panel_settings',
    route: '/superadmin',
    roles: ['admin'],
  },
  {
    label: 'WooCommerce',
    translationKey: 'NAV.WOOCOMMERCE',
    icon: 'shopping_cart',
    route: '/woocommerce',
    roles: ['admin', 'manager'],
  },
];
